name: Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Doxygen documentation
      run: |
        cd portfolio/doxygen
        doxygen Doxyfile

    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: doxygen-docs
        path: portfolio/doxygen/docs/html
